language: node_js
node_js:
  - "7"
sudo:
  - required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm i -g gulp
  - npm i
services:
  - mongodb
script:
  - cp .env.prod .env
  - gulp travis
after_success:
  - npm run coveralls
